#!/usr/bin/env ruby

ENV["RAILS_ENV"] ||= "test"
require "pathname"
require "cypress-rails"
require "cypress-rails/open_ct"
require "cypress-rails/run_ct"
require Pathname.new(CypressRails::Config.new.dir).join("config/environment")

command = ARGV[0]
case command
when "init"
  CypressRails::Init.new.call
when "open"
  CypressRails::Open.new.call
when "run"
  passed = CypressRails::Run.new.call
  exit 1 unless passed

when "open-ct"
  CypressRails::OpenCt.new.call
when "run-ct"
  passed = CypressRails::RunCt.new.call
  exit 1 unless passed
end
